# THIS FILE IS AUTOMATICALLY GENERATED
# Project: D:\PSoC_Projects\Spectrometers\PSoC-ColorSensors_Spectrometers\AS7262\AS7262.cydsn\AS7262.cyprj
# Date: Sun, 25 Mar 2018 00:12:02 GMT
#set_units -time ns
create_clock -name {CyILO} -period 10000 -waveform {0 5000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyMASTER_CLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]
create_generated_clock -name {timer_clock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 4801 9601} [list [get_pins {ClockBlock/dclk_glb_0}]]

set_false_path -from [get_pins {__ONE__/q}]

# Component constraints for D:\PSoC_Projects\Spectrometers\PSoC-ColorSensors_Spectrometers\AS7262\AS7262.cydsn\TopDesign\TopDesign.cysch
# Project: D:\PSoC_Projects\Spectrometers\PSoC-ColorSensors_Spectrometers\AS7262\AS7262.cydsn\AS7262.cyprj
# Date: Sun, 25 Mar 2018 00:11:54 GMT
