# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Kyle\Documents\PSoC Creator\Spectrometers\AS7262\AS7262_psoc4.cydsn\AS7262_psoc4.cyprj
# Date: Mon, 22 Jan 2018 06:38:31 GMT
#set_units -time ns
create_clock -name {I2C_SCBCLK(FFB)} -period 625 -waveform {0 312.5} [list [get_pins {ClockBlock/ff_div_2}]]
create_clock -name {UART_SCBCLK(FFB)} -period 729.16666666666663 -waveform {0 364.583333333333} [list [get_pins {ClockBlock/ff_div_5}]]
create_clock -name {CyRouted1} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFClk} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {I2C_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 31 61} [list]
create_generated_clock -name {UART_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 35 71} [list]


# Component constraints for C:\Users\Kyle\Documents\PSoC Creator\Spectrometers\AS7262\AS7262_psoc4.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Kyle\Documents\PSoC Creator\Spectrometers\AS7262\AS7262_psoc4.cydsn\AS7262_psoc4.cyprj
# Date: Mon, 22 Jan 2018 06:38:28 GMT
